backend:
  name: github
  repo: sleakops/docs
  branch: dev
  base_url: https://sveltia-cms-auth.matias-izquierdo.workers.dev

media_folder: static/img
public_folder: /img

collections:
  - name: docs-root
    label: "Root Documentation"
    folder: docs
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: pagination_prev, label: Previous Page, widget: string, required: false }
      - { name: pagination_next, label: Next Page, widget: string, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: cluster
    label: "ðŸ–¥ï¸ Cluster"
    folder: docs/cluster
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: cluster-addons
    label: "ðŸ–¥ï¸ Cluster > Addons"
    folder: docs/cluster/addons
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: cluster-nodepools
    label: "ðŸ–¥ï¸ Cluster > Nodepools"
    folder: docs/cluster/nodepools
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: domain
    label: "ðŸŒ Domain"
    folder: docs/domain
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: environment
    label: "ðŸ”§ Environment"
    folder: docs/environment
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: network
    label: "ðŸ”— Network"
    folder: docs/network
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: project
    label: "ðŸ“¦ Project"
    folder: docs/project
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: project-build
    label: "ðŸ“¦ Project > Build"
    folder: docs/project/build
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: project-chart
    label: "ðŸ“¦ Project > Chart"
    folder: docs/project/chart
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: project-dependency
    label: "ðŸ“¦ Project > Dependency"
    folder: docs/project/dependency
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: project-deployment
    label: "ðŸ“¦ Project > Deployment"
    folder: docs/project/deployment
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: project-vargroup
    label: "ðŸ“¦ Project > Vargroup"
    folder: docs/project/vargroup
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: project-workload
    label: "ðŸ“¦ Project > Workload"
    folder: docs/project/workload
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: provider
    label: "â˜ï¸ Provider"
    folder: docs/provider
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: quickstart
    label: "ðŸš€ Quickstart"
    folder: docs/quickstart
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: quickstart-django_celery
    label: "ðŸš€ Quickstart > Django Celery"
    folder: docs/quickstart/django_celery
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: quickstart-n8n
    label: "ðŸš€ Quickstart > N8N"
    folder: docs/quickstart/n8n
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: user
    label: "ðŸ‘¤ User"
    folder: docs/user
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_label, label: Sidebar Label, widget: string, required: false }
      - { name: sidebar_position, label: Sidebar Position, widget: number, required: false }
      - { name: body, label: Body, widget: markdown }

