backend:
  name: github
  repo: sleakops/docs
  branch: develop
  base_url: https://sveltia-cms-auth.matias-izquierdo.workers.dev

media_folder: static/img
public_folder: /img

collections:
  - name: docs-root
    label: "Root Documentation"
    folder: docs
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - {
          name: pagination_prev,
          label: Previous Page,
          widget: string,
          required: false,
        }
      - {
          name: pagination_next,
          label: Next Page,
          widget: string,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: cluster
    label: "üñ•Ô∏è Cluster"
    folder: docs/cluster
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: cluster-addons
    label: "üñ•Ô∏è Cluster > Addons"
    folder: docs/cluster/addons
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: cluster-nodepools
    label: "üñ•Ô∏è Cluster > Nodepools"
    folder: docs/cluster/nodepools
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: domain
    label: "üåê Domain"
    folder: docs/domain
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: environment
    label: "üîß Environment"
    folder: docs/environment
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: network
    label: "üîó Network"
    folder: docs/network
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: project
    label: "üì¶ Project"
    folder: docs/project
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: project-build
    label: "üì¶ Project > Build"
    folder: docs/project/build
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: project-chart
    label: "üì¶ Project > Chart"
    folder: docs/project/chart
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: project-dependency
    label: "üì¶ Project > Dependency"
    folder: docs/project/dependency
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: project-deployment
    label: "üì¶ Project > Deployment"
    folder: docs/project/deployment
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: project-vargroup
    label: "üì¶ Project > Vargroup"
    folder: docs/project/vargroup
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: project-workload
    label: "üì¶ Project > Workload"
    folder: docs/project/workload
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: provider
    label: "‚òÅÔ∏è Provider"
    folder: docs/provider
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: quickstart
    label: "üöÄ Quickstart"
    folder: docs/quickstart
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: quickstart-django_celery
    label: "üöÄ Quickstart > Django Celery"
    folder: docs/quickstart/django_celery
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: quickstart-n8n
    label: "üöÄ Quickstart > N8N"
    folder: docs/quickstart/n8n
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: user
    label: "üë§ User"
    folder: docs/user
    create: true
    extension: mdx
    format: frontmatter
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: sidebar_label,
          label: Sidebar Label,
          widget: string,
          required: false,
        }
      - {
          name: sidebar_position,
          label: Sidebar Position,
          widget: number,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: tutorials
    label: "üìö Tutorials"
    folder: tutorials
    create: true
    extension: mdx
    format: frontmatter
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - name: sidebar_label
        label: Sidebar Label
        widget: string
        required: false
      - name: sidebar_position
        label: Sidebar Position
        widget: number
        required: false
        value_type: int
        min: 0
      - { name: description, label: Description, widget: text, required: true }
      - name: tags
        label: Tags
        widget: select
        multiple: true
        options:
          - { label: "‚≠ê Featured", value: "featured" }
          - { label: "Next.js", value: "nextjs" }
          - { label: "Node.js", value: "node" }
          - { label: "PHP", value: "php" }
          - { label: "Database", value: "database" }
        required: false
      - name: image
        label: Preview Image
        widget: image
        required: false
        multiple: false
      - { name: body, label: Body, widget: markdown }

  - name: changelog
    label: "üìù Changelog"
    folder: changelog
    create: true
    extension: md
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: slug, label: Slug, widget: string }
      - name: authors
        label: Authors
        widget: list
        fields:
          - { name: name, label: Name, widget: string }
          - { name: title, label: Title, widget: string, required: false }
      - name: tags
        label: Tags
        widget: select
        multiple: true
        options:
          - { label: "Release", value: "release" }
          - { label: "Major", value: "major" }
          - { label: "Minor", value: "minor" }
          - { label: "Patch", value: "patch" }
          - { label: "Feature", value: "feature" }
          - { label: "Bugfix", value: "bugfix" }
        required: false
      - { name: body, label: Body, widget: markdown }
